---
# vi: ts=2 sw=2 et:
#
name: Build test
on:
  pull_request:
    paths:
      - '**/meson.build'
      - '.github/workflows/**'
      - 'meson_options.txt'
      - 'src/**'
      - 'test/fuzz/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env.COMPILER }}-${{ matrix.env.COMPILER_VERSION }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        env:
          - { COMPILER: "gcc",   COMPILER_VERSION: "10" }
          - { COMPILER: "gcc",   COMPILER_VERSION: "11" }
          - { COMPILER: "clang", COMPILER_VERSION: "10" }
          - { COMPILER: "clang", COMPILER_VERSION: "11" }
          - { COMPILER: "clang", COMPILER_VERSION: "12" }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Build check (${{ env.COMPILER }}-${{ env.COMPILER_VERSION }})
        run: sudo -E .github/workflows/build_test.sh
