---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
#
name: Build test
on:
  pull_request:
    paths:
      - '**/meson.build'
      - '.github/workflows/**'
      - 'meson_options.txt'
      - 'src/**'
      - 'test/fuzz/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env.COMPILER }}-${{ matrix.env.COMPILER_VERSION }}-${{ matrix.env.LINKER }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        env:
          - { COMPILER: "gcc",   COMPILER_VERSION: "10", LINKER: "bfd"  }
          - { COMPILER: "gcc",   COMPILER_VERSION: "11", LINKER: "gold" }
          - { COMPILER: "clang", COMPILER_VERSION: "11", LINKER: "bfd"  }
          - { COMPILER: "clang", COMPILER_VERSION: "12", LINKER: "gold" }
          - { COMPILER: "clang", COMPILER_VERSION: "13", LINKER: "lld"  }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Build check (${{ env.COMPILER }}-${{ env.COMPILER_VERSION }}-${{ env.LINKER }})
        run: sudo -E .github/workflows/build_test.sh
