---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
# https://github.com/marketplace/actions/super-linter
name: Lint Code Base

on:
  pull_request:
    branches:
      - main
      - v[0-9]+-stable

permissions:
  contents: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Repo checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          # We need a full repo clone
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@454ba4482ce2cd0c505bc592e83c06e1e37ade61
        env:
          DEFAULT_BRANCH: main
          MULTI_STATUS: false
          # Excludes:
          #   - man/.* - all snippets in man pages (false positives due to
          #              missing shebangs)
          #   - .*\.(in|SKELETON) - all template/skeleton files
          #                         except kernel-install
          FILTER_REGEX_EXCLUDE: .*/(man/.*|([^k]|k(k|ek)*([^ek]|e[^kr]))*(k(k|ek)*e?)?\.(in|SKELETON))$
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_GITHUB_ACTIONS: true
